version: "3.8"
services:
  app:
    build: .
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    ports:
      - "8000:8000"
      - "1935:1935"
    volumes:
      - .:/app
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]

  rtmp:
    image: tiangolo/nginx-rtmp
    ports:
      - "1935:1935"
    environment:
      - STREAM_KEY=somekey

